CREATE DATABASE Localidades;

USE Localidades;

CREATE TABLE IF NOT EXISTS Estado(
ID INT AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
UF VARCHAR(2) NOT NULL, 
PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS Cidade (
ID INT AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
ESTADO_ID INT,
PRIMARY KEY (ID),
FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO (ID)
);


INSERT INTO ESTADO (ID, NOME, UF) VALUES
	(1, 'São Paulo','SP'),
    (2, 'Rio de Janeiro','RJ'),
    (3, 'Bahia','BA');
    
INSERT INTO CIDADE (ID, NOME, ESTADO_ID) VALUES
	(1,'São Paulo',1),
    (2, 'Campinas',1),
    (3,'Rio de Janeiro',2),
    (4,'Arraial do Cabo',2),
    (5,'Salvador',3),
    (6,'Ilhéus',3),
    (7,'Night City', null),
    (8,'Gothan City', null);
    
SELECT * FROM CIDADE;
    
SELECT * FROM ESTADO;

-- ----------
-- Consultas SQL com JOINs
-- ---------- 

SELECT CIDADE.Nome, ESTADO.Nome AS Estado_Nome, ESTADO.UF
FROM CIDADE
INNER JOIN ESTADO ON CIDADE.Estado_ID = ESTADO.ID;

CREATE TABLE IF NOT EXISTS Prefeito (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
DATAPOSSE DATE NOT NULL
);

INSERT INTO PREFEITO (NOME, DATAPOSSE) VALUES

('João da Silva', '2024-01-01'),
('Maria Oliveira', '2023-01-01'),
('Carlos Santos', '2022-01-01');

UPDATE CIDADE
SET PREFEITO_ID = 1
WHERE NOME = 'São Paulo';

UPDATE CIDADE
SET PREFEITO_ID = 2
WHERE ID = 5;

UPDATE CIDADE
SET PREFEITO_ID = 3
WHERE ESTADO_ID = 3 AND ID = 3;

SELECT * FROM PREFEITO






