USE LOCALIDADES;

-- --------------------------------------------------------------------------
#1
-- FAÇA UMA JUNÇÃO DA TABELA CIDADE	E ESTADO, MOSTRANDO:
-- NOME DA CIDADE, SIGLA DO ESTADO. APENAS NAS CIDADES QUE TEM ESTADO

SELECT CIDADE.NOME, ESTADO.SIGLA FROM CIDADE
INNER JOIN ESTADO ON CIDADE.ID = ESTADO.ID;

-- --------------------------------------------------------------------------
#2 
-- FAÇA UMA JUNÇÃO DA TABELA CIDADE E ESTADO, MOSTRANDO:
-- NOME DA CIDADE, SIGLA DO ESTADO. TODAS AS CIDADES, INDEPENDENTE DE TEREM ESTADO

SELECT CIDADE.NOME, ESTADO.SIGLA FROM CIDADE
LEFT JOIN ESTADO ON CIDADE.ID = ESTADO.ID;

-- --------------------------------------------------------------------------
#3
-- FAÇA UMA JUNÇÃO DA TABELA CIDADE E ESTADO MOSTRANDO:
-- NOME DA CIDADE, SIGLA DO ESTADO. MOSTRE TODOS OS ESTADOS, INDEPENDENTE DE TEREM CIDADES

SELECT ESTADO.SIGLA, CIDADE.NOME FROM CIDADE
LEFT JOIN ESTADO ON CIDADE.ID = ESTADO.ID;

SELECT CIDADE.NOME, ESTADO.SIGLA FROM CIDADE
RIGHT JOIN ESTADO ON CIDADE.ID = ESTADO.ID;
 -- --------------------------------------------------------------------------
 #4
 -- FAÇA UMA JUNÇÃO DA TABELA CIDADE, ESTADO E PREFEITO:
 -- CIDADE.NOME, ESTADO.SIGLA/UF, PREFEITO.NOME, PREFEITO.DATAPOSSE
 -- PARA TODAS AS CIDADES QUE TEM PREFEITO
 
 SELECT CIDADE.NOME, ESTADO.SIGLA, PREFEITO.NOME, PREFEITO.DATAPOSSE  FROM CIDADE
 INNER JOIN ESTADO ON CIDADE.ID = ESTADO.ID
 INNER JOIN PREFEITO ON PREFEITO.ID = ESTADO.ID;
 
 -- --------------------------------------------------------------------------
# 1º
SELECT * FROM CIDADE;
SELECT * FROM ESTADO;